build:
	gcc 1_Process.c -o pro_one
	gcc 1_Systemcall.c -o sys_one
	gcc 1_Thread.c -o th_one
	gcc 2_Systemcall.c -o sys_two
	gcc 2_Process.c -o pro_two
	gcc 2_Thread.c -o th_two
	gcc 3_Systemcall.c -o sys_three
