build:
	gcc Client_string.c -o one -lrt
	gcc Server_string.c -o two -lrt
	gcc Pro_Con_Stack_semaphore -o stack -lpthread
	gcc Pro_Con_Stack_mutex -o mutex -lpthread
	gcc sender_5.c -o send2 -lrt
	gcc rec_5.c -o rec2 -lrt
	gcc SharedMemory. -o shared -lrt
	gcc Queue_Sem.c -o Sema -lpthread
	gcc Queue_Mutex.c -o mque -lpthread



